### ISSUE TITLE
메일 백업 중에 502 에러 발생

### ISSUE THREAD

**Issue by kirinbeer** [coloriz/izms#5]
메일 다운로드 열심히 돌아가고 있는 중에 아래와 같은 에러가 뜨면서 백업이 중단되는데요, 무슨 방법이 있을까요 ? ㅜ

==> Downloading a new mail m15975
m15975: キム・チェウォン / 🐻🐻 / 2021-01-10 20:34:09
Traceback (most recent call last):
  File "D:\Temp\ScrapMaster5\izone-mail-shelter-master\run.py", line 99, in <module>
    main()
  File "D:\Temp\ScrapMaster5\izone-mail-shelter-master\run.py", line 75, in main
    mail_detail = app.get_mail_detail(mail.id)
  File "D:\Temp\ScrapMaster5\izone-mail-shelter-master\izonemail\izonemail.py", line 121, in get_mail_detail
    res.raise_for_status()
  File "C:\Users\YHB\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://app-web.izone-mail.com/mail/m15975

**Comment by coloriz** [comment]
HTTP 502 에러는 서버쪽 게이트웨이 통신에서 에러가 발생했을 때 반환됩니다.
요즘 백업하는 분들이 많아지고 서버측의 트래픽이 급증하여 그런 것이 아닐까 추측해봅니다..

해결방안은 서버의 network congestion이 해소될 때까지 기다리는 것뿐이며,
트래픽이 적을 것으로 예상되는 새벽에 다시 시도해보시기 바랍니다.

추가적으로, #4 에 언급되었듯이, 현재 구현된 로직은 메일을 가장 최근 것부터 다운로드합니다.
따라서 중간에 끊겼을 경우 같은 `download_path`로 재실행하면 더 이상 다운받을 메일이 없다고 뜰 수 있습니다.
그러므로 재시도하실 때는 `download_path`에 지정한 폴더의 내용물을 삭제하거나 아예 패스를 변경하시길 권해드립니다.

일단 한번 전체 덤핑이 완료된 후에는, 재실행했을 경우 서버의 메일함과 비교하여 로컬에 없는 메일만 받아옵니다.
참고하시기 바랍니다.

**Comment by coloriz** [comment]
이제 제일 오래된 메일부터 다운로드됩니다.
다운로드 중 예외가 발생하더라도 이어서 다운로드 받을 수 있습니다.
